### ML Review, Text, Keras

- Review LogisticRegression with Text Data
- Introduce Keras and ANN

In [2]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron

In [3]:
from sklearn.datasets import load_breast_cancer

In [4]:
cancer = load_breast_cancer()

In [5]:
X = cancer.data
y = cancer.target

In [6]:
mlp = multilayer_perceptron.MLPClassifier()

In [7]:
mlp.fit(X, y)

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier()

In [8]:
mlp.predict(X)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

### Sklearn `Perceptron`

In [9]:
perceptron = Perceptron()

In [10]:
perceptron.fit(X, y)

Perceptron()

In [11]:
perceptron.predict(X)

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [12]:
from keras import models
from keras import layers

Using TensorFlow backend.


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
from sklearn.datasets import fetch_20newsgroups_vectorized

In [15]:
news = fetch_20newsgroups_vectorized()

In [23]:
X = news.data
y = news.target

In [30]:
y

array([17,  7, 10, ..., 14, 12, 11])

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
ohe = OneHotEncoder()
y = ohe.fit_transform(y.reshape(-1,1))

In [34]:
X

<11314x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [35]:
model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(X.shape[1],)))
model.add(layers.Dense(20, activation= 'softmax'))

In [36]:
model.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [37]:
import pandas as pd

In [38]:
history = model.fit(X, y, epochs = 5)

Epoch 1/5
11314/11314 [==============================] - 20s 2ms/step - loss: 2.4729 - accuracy: 0.6098
Epoch 2/5
11314/11314 [==============================] - 21s 2ms/step - loss: 1.2123 - accuracy: 0.8598
Epoch 3/5
11314/11314 [==============================] - 20s 2ms/step - loss: 0.5760 - accuracy: 0.9180
Epoch 4/5
11314/11314 [==============================] - 20s 2ms/step - loss: 0.3226 - accuracy: 0.9475
Epoch 5/5
11314/11314 [==============================] - 21s 2ms/step - loss: 0.2030 - accuracy: 0.9645


In [39]:
history.history['loss']

[2.472927850127663,
 1.2123152187862265,
 0.5759644422437142,
 0.3225520170101623,
 0.2030251544124987]

In [40]:
model.predict(X)

array([[1.2609179e-05, 3.1751267e-07, 2.6379229e-08, ..., 9.9968386e-01,
        4.4540859e-05, 1.5380490e-04],
       [2.2154484e-06, 4.8326933e-06, 1.2645752e-06, ..., 4.4112406e-07,
        4.5139124e-05, 1.1178345e-05],
       [2.2297867e-07, 3.6282273e-09, 6.2569372e-09, ..., 1.4068829e-07,
        3.7959799e-07, 6.3745702e-08],
       ...,
       [6.4438867e-04, 4.5650449e-01, 2.9788882e-02, ..., 2.5899810e-04,
        1.2812896e-03, 2.0693801e-03],
       [1.6568592e-04, 2.7777664e-02, 1.2202883e-02, ..., 2.4706336e-05,
        3.1695626e-04, 7.1760960e-04],
       [2.9376067e-06, 3.4980769e-07, 6.9382416e-08, ..., 2.5844244e-07,
        5.4257511e-05, 1.3165520e-06]], dtype=float32)

In [41]:
def network_modeler(X, y):
    import numpy as np
    cvect = CountVectorizer(stop_words = 'english', max_features = 1000)
    xvect = cvect.fit_transform(X)
    yhot = OneHotEncoder()
    yohe = yhot.fit_transform(y)
    
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu', input_shape=(xvect.shape[1],)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(len(np.unique(y)), activation= 'softmax'))
    model.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    history = model.fit(xvect, yohe, epochs = 10)
    return history
    

In [42]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(h.history['loss'])

NameError: name 'h' is not defined

In [ ]:
plt.plot(h.history['accuracy'])

In [ ]:
y.mean()